# permissions for end users to view starships.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: starship-viewer-role
rules:
- apiGroups:
  - starships.starwars.julienstroheker.com
  resources:
  - starships
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starships.starwars.julienstroheker.com
  resources:
  - starships/status
  verbs:
  - get
